# Static MSVC CRT linking.
#
# Without this setting the Rust MSVC build links the Visual C++ runtime
# dynamically (VCRUNTIME140.dll, MSVCP140.dll …). On a fresh Windows Server
# or a minimal workstation without the "Visual C++ Redistributable"
# packages installed, the EXE fails at startup with "VCRUNTIME140.dll was
# not found". Because Stars ships as a standalone tool (see release note:
# "no additional software required"), the CRT must be statically linked
# into the EXE.

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
